version: '3.1'

services:
  mongo:
    image: mongo
    container_name: video_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: newpass
    volumes: 
     - ~/mongodb_data:/data/db
    ports: 
      - 27017:27017
      # 添加运行命令
    # command: mongod --smallfiles --logpath=/dev/null # --quiet



  mongo-express:
    image: mongo-express
    container_name: video_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: newpass