web:
  image: nginx
  volumes: 
    - ~/Desktop/hello_docker/nginx/html:/usr/share/nginx/html
    - ~/Desktop/hello_docker/nginx/conf.d:/etc/nginx/conf.d
  ports: 
   - "8080:80" 
  environment: 
    - NGINX_PORT=80

