version: '3.1'
services: 
  db:
    container_name: compose-mysql
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: newpass

  adminer:
      container_name: mysql-admin
      image: adminer
      restart: always
      ports:
       - 8082:8080





