version: '3.1'
services: 
  db:
    container_name: compose-mysql
    image: mysql:5.6
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - hello_flask.sql:/data/hello_flask.sql
    environment:
      MYSQL_ROOT_PASSWORD: newpass
    command: bash -c "mysql -uroot -pnewpass hello_flask < /data/hello_flask.sql "
    # command: bash -c "mysql -uroot -pnewpass hello_flask < /data/hello_flask.sql&& --default-authentication-plugin=mysql_native_password"
  # adminer:
  #     container_name: mysql-admin
  #     environment: 
  #       MYSQL_ROOT_PASSWORD: newpass
  #     links: 
  #       - "db:db"
  #     image: adminer
  #     restart: always
  #     ports:
  #      - 8082:8080
volumes: 
  hello_flask.sql:





